-- AlterTable
ALTER TABLE "Purchase" ALTER COLUMN "tds" DROP NOT NULL,
ALTER COLUMN "tds" DROP DEFAULT,
ALTER COLUMN "rem" DROP NOT NULL,
ALTER COLUMN "rem" DROP DEFAULT,
ALTER COLUMN "paymentFrom" SET DATA TYPE TEXT;
